image: ruby:3.3.1
include:
  - template: Code-Quality.gitlab-ci.yml
services:
  - postgres:9.5
  - docker:dind  

variables:
  POSTGRES_DB: db_test
  POSTGRES_USER: webapi
  POSTGRES_PASSWORD: <POSTGRES_PASSWORD>
  TEST_DB_URL: <TEST_DB_URL>
  DB_HOST: postgres
  TEAM: gondor

stages:
  - build
  - package
  - deploy_test
  - acceptance_test
  - deploy_prod

code_quality:
  stage: build
  artifacts:
    paths: [gl-code-quality-report.json]

build_job:
  stage: build
  script:
    - gem install bundler --no-document
    - bundle install --without staging production
    - APP_MODE=test bundle exec rake ci
    - bundle exec rake version > VERSION.txt
  artifacts:
    when: always
    paths:
      - VERSION.txt
      - reports/
    reports:
      junit: reports/spec/rspec.xml

package_job:
  stage: package
  image: docker:stable
  before_script:
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  script:
    - VERSION=$(cat VERSION.txt)
    - echo $VERSION
    - docker build -f Dockerfile.prod --build-arg GIT_COMMIT=$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:$VERSION .
    - docker tag $CI_REGISTRY_IMAGE:$VERSION $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$VERSION
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - tags

deploy_test_job:
  stage: deploy_test
  image: nicopaez/kubectl:1.28.0
  environment: test
  script:
    - VERSION=$(cat VERSION.txt)
    - cp ${KUBECONFIG} $HOME/.kube/config
    - kubectl -n ${TEAM}-${CI_ENVIRONMENT_NAME} apply -f infra/${CI_ENVIRONMENT_NAME}.configmap.yaml
    - kubectl -n ${TEAM}-${CI_ENVIRONMENT_NAME} set image deployment/restapi restapi=$CI_REGISTRY_IMAGE:$VERSION
    - ./scripts/smoke_test.sh <API_TEST_URL> $VERSION
  only:
    - tags

deploy_prod_job:
  stage: deploy_prod
  image: nicopaez/kubectl:1.28.0
  environment: prod
  script:
    - VERSION=$(cat VERSION.txt)
    - cp ${KUBECONFIG} $HOME/.kube/config
    - kubectl -n ${TEAM}-${CI_ENVIRONMENT_NAME} apply -f infra/${CI_ENVIRONMENT_NAME}.configmap.yaml
    - kubectl -n ${TEAM}-${CI_ENVIRONMENT_NAME} set image deployment/restapi restapi=$CI_REGISTRY_IMAGE:$VERSION
    - ./scripts/smoke_test.sh <API_PROD_URL> $VERSION
  only:
    - tags
  when: manual

acceptance_job:
  stage: acceptance_test
  environment: test
  variables:
    DISABLE_SIMPLECOV_THRESHOLD: "true"
  script:
    - gem install bundler --no-document
    - bundle install --without staging production
    - APP_MODE=test bundle exec rake spec_regression
  only:
    - tags
    